CREATE TABLE IF NOT EXISTS `Puffles` (
  `ID` mediumint(8) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Puffle ID',
  `Owner` int(11) unsigned NOT NULL COMMENT 'Owner''s player ID',
  `Name` tinytext NOT NULL COMMENT 'Puffle name',
  `Type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Puffle type',
  `Hunger` tinyint(3) unsigned NOT NULL DEFAULT '100' COMMENT 'Puffle''s hunger status',
  `Health` tinyint(3) unsigned NOT NULL DEFAULT '100' COMMENT 'Puffle''s health status',
  `Rest` tinyint(3) unsigned NOT NULL DEFAULT '100' COMMENT 'Puffle''s rest status',
  `Walking` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Puffle''s walking status',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 COMMENT='Contains data regarding user puffles';

CREATE TABLE IF NOT EXISTS `Stats` (
  `ID` tinyint(3) unsigned NOT NULL COMMENT 'Server ID',
  `Population` smallint(5) unsigned NOT NULL COMMENT 'Server''s Population',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Server statistics';

CREATE TABLE IF NOT EXISTS `users` (
 `ID` int(10) NOT NULL AUTO_INCREMENT,
  `Username` char(12) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nickname',
  `Password` varchar(240) NOT NULL COMMENT 'Password hash',
  `Email` char(128) NOT NULL,
  `RegisteredTime` int(11) NOT NULL COMMENT 'Unix timestamp',
  `LoginKey` char(40) DEFAULT '' COMMENT 'Used for logging into the game server',
  `Active` tinyint(1) unsigned NOT NULL DEFAULT 1,
  `Status` varchar(240) NOT NULL DEFAULT '' COMMENT 'Contains the player''s online status',
  `Coins` int(10) unsigned NOT NULL DEFAULT 10000 COMMENT 'Player coins',
  `Color` varchar(12) NOT NULL DEFAULT '1' COMMENT 'Current color item',
  `Head` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current head item',
  `Face` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current face item',
  `Neck` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current neck item',
  `Body` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current body item',
  `Hand` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current hand item',
  `Feet` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current feet item',
  `Photo` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current photo item',
  `Buddies` varchar(240) NOT NULL DEFAULT '' COMMENT 'Player buddies',
  `Flag` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Current flag item',
  `Ignores` varchar(240) NOT NULL DEFAULT '' COMMENT 'Player''s ignored list',
  `Inventory` varchar(240) DEFAULT '' COMMENT 'Player inventory',
  `Igloo` tinyint(2) unsigned NOT NULL DEFAULT 1 COMMENT 'Current igloo ID',
  `Igloos` varchar(240) NOT NULL DEFAULT '' COMMENT 'Player''s owned igloos',
  `Music` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT 'Current music ID',
  `Floor` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Current flooring ID',
  `RoomFurniture` varchar(240) NOT NULL DEFAULT '' COMMENT 'Igloo furniture',
  `Furniture` varchar(240) NOT NULL DEFAULT '' COMMENT 'Furniture inventory',
  `Postcards` varchar(240) NOT NULL DEFAULT '\'0\'' COMMENT 'Player postcards',
  `Title` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Nameglow` varchar(240) NOT NULL DEFAULT '\'0\'' ,
  `Namecolor` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Text` mediumtext NOT NULL DEFAULT '\'0\'',
  `Bubblecolor` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Penguinglow` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Snowballglow` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Ringcolor` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Chatglow` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Moodcolor` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Moodglow` varchar(240) NOT NULL DEFAULT '\'0\'',
  `Speed` int(3) NOT NULL DEFAULT '4',
  `Mood` char(100) NOT NULL DEFAULT 'I have a mood',
  `Size` int(3) NOT NULL DEFAULT '100',
  `Alpha` int(3) NOT NULL DEFAULT '100',
  `Moderator` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Player''s moderator status',
  `Rank` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT 'Player''s rank (badge when multiplied by 146)',
  `LastLogin` int(11) unsigned DEFAULT NULL COMMENT 'Unix timestamp',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Username` (`Username`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 COMMENT='This is the table in which all player data is stored.';
